FROM node:14.5-alpine as builder

## Install build toolchain, install node deps and compile native add-ons
#RUN npm install [ your npm dependencies here ]
COPY package*.json /

RUN npm ci --production

FROM node:14.5-alpine as app

# add curl for 
RUN apk --no-cache add curl

## Copy built node modules and binaries without including the toolchain
COPY --from=builder node_modules /app/node_modules

#COPY (?!(node_modules|\.)) /
COPY . /app

WORKDIR /app

USER node

#ENV TEMP_FILE_PATH
#ENV SECRET
#ENV MONGODB_URI

HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 CMD curl --fail http://localhost:3000/ || exit 1

CMD ["node","server.js"]

# docker build . -t mdnmdn/sample-app:v1-backend
# docker push mdnmdn/sample-app:v1-backend
