FROM alpine:3.10
#FROM busybox:1.31

#ENTRYPOINT ["sh","-c","echo -- The ENTRYPOINT! $(date)  "]

CMD ["sh","-c","echo -- The CMD! $(date)  "]

#ENTRYPOINT ["echo",">> I'm the ENTRYPOINT!"]
#CMD ["echo",">> I'm the CMD!"]

# docker build -t sample-cmd:v1 .
# docker tag sample-cmd:v1 mdnmdn/sample-cmd:v1
# docker push mdnmdn/sample-cmd:v1

